Aeroporto2/config/routes.rb
Rails.application.routes.draw do
  resources :routes
  resources :companies
  resources :passages
  resources :clients

end

Aeroporto2/app/models/client.rb
class Client < ActiveRecord::Base
end

Aeroporto2/app/models/company.rb
class Company < ActiveRecord::Base
end

Aeroporto2/app/models/passage.rb
class Passage < ActiveRecord::Base
	belongs_to :client
	belongs_to :company
	belongs_to :route
end

Aeroporto2/app/models/route.rb
class Route < ActiveRecord::Base
end

Aeroporto2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Aeroporto2/app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :cpf)
    end
end

Aeroporto2/app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :cnpj)
    end
end

Aeroporto2/app/controllers/passages_controller.rb
class PassagesController < ApplicationController
  before_action :set_passage, only: [:show, :edit, :update, :destroy]

  # GET /passages
  # GET /passages.json
  def index
    @passages = Passage.all
  end

  # GET /passages/1
  # GET /passages/1.json
  def show
  end

  # GET /passages/new
  def new
    @passage = Passage.new
  end

  # GET /passages/1/edit
  def edit
  end

  # POST /passages
  # POST /passages.json
  def create
    @passage = Passage.new(passage_params)

    respond_to do |format|
      if @passage.save
        format.html { redirect_to @passage, notice: 'Passage was successfully created.' }
        format.json { render :show, status: :created, location: @passage }
      else
        format.html { render :new }
        format.json { render json: @passage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passages/1
  # PATCH/PUT /passages/1.json
  def update
    respond_to do |format|
      if @passage.update(passage_params)
        format.html { redirect_to @passage, notice: 'Passage was successfully updated.' }
        format.json { render :show, status: :ok, location: @passage }
      else
        format.html { render :edit }
        format.json { render json: @passage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passages/1
  # DELETE /passages/1.json
  def destroy
    @passage.destroy
    respond_to do |format|
      format.html { redirect_to passages_url, notice: 'Passage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passage
      @passage = Passage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def passage_params
      params.require(:passage).permit(:font, :destiny, :client_id, :company_id, :route_id)
    end
end

Aeroporto2/app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  # GET /routes
  # GET /routes.json
  def index
    @routes = Route.all
  end

  # GET /routes/1
  # GET /routes/1.json
  def show
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes
  # POST /routes.json
  def create
    @route = Route.new(route_params)

    respond_to do |format|
      if @route.save
        format.html { redirect_to @route, notice: 'Route was successfully created.' }
        format.json { render :show, status: :created, location: @route }
      else
        format.html { render :new }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url, notice: 'Route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_params
      params.require(:route).permit(:hour, :price, :status)
    end
end

Aeroporto2/app/helpers/application_helper.rb
module ApplicationHelper
end

Aeroporto2/app/helpers/clients_helper.rb
module ClientsHelper
end

Aeroporto2/app/helpers/companies_helper.rb
module CompaniesHelper
end

Aeroporto2/app/helpers/passages_helper.rb
module PassagesHelper
end

Aeroporto2/app/helpers/routes_helper.rb
module RoutesHelper
end

Aeroporto2/app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cpf %><br>
    <%= f.text_field :cpf %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Aeroporto2/app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

Aeroporto2/app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1> Listando clientes </h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cpf</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.cpf %></td>
        <td><%= link_to 'Mostrar', client %></td>
        <td><%= link_to 'Editar', edit_client_path(client) %></td>
        <td><%= button_to 'Destruir', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Cliente', new_client_path %>

Aeroporto2/app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

Aeroporto2/app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @client.cpf %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

Aeroporto2/app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cnpj %><br>
    <%= f.text_field :cnpj %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Aeroporto2/app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

Aeroporto2/app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listando companhias</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cnpj</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.cnpj %></td>
        <td><%= link_to 'Mostrar', company %></td>
        <td><%= link_to 'Editar', edit_company_path(company) %></td>
        <td><%= button_to 'Destruir', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova companhia', new_company_path %>

Aeroporto2/app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

Aeroporto2/app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Cnpj:</strong>
  <%= @company.cnpj %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

Aeroporto2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aeroporto2</title>
</head>
<body>

<%= yield %>

</body>
</html>

Aeroporto2/app/views/passages/_form.html.erb
<%= form_for(@passage) do |f| %>
  <% if @passage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@passage.errors.count, "error") %> prohibited this passage from being saved:</h2>

      <ul>
      <% @passage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :client %><br>
    <%= collection_select(:passage, :client_id, Client.all, :id, :cpf) %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= collection_select(:passage, :company_id, Company.all, :id, :cnpj) %>
  </div>
  <div class="field">
    <%= f.label :Route %><br>
    <%= collection_select(:passage, :route_id, Route.all, :id, :hour) %>
  </div>
  <div class="field">
    <%= f.label :font %><br>
    <%= f.text_field :font %>
  </div>
  <div class="field">
    <%= f.label :destiny %><br>
    <%= f.text_field :destiny %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Aeroporto2/app/views/passages/edit.html.erb
<h1>Editing Passage</h1>

<%= render 'form' %>

<%= link_to 'Show', @passage %> |
<%= link_to 'Back', passages_path %>

Aeroporto2/app/views/passages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listandos passagens</h1>

<table>
  <thead>
    <tr>
      <th>Fonte</th>
      <th>Destino</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @passages.each do |passage| %>
      <tr>
        <td><%= passage.font %></td>
        <td><%= passage.destiny %></td>
        <td><%= link_to 'Mostrar', passage %></td>
        <td><%= link_to 'Editar', edit_passage_path(passage) %></td>
        <td><%= button_to 'Destruir', passage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova passagem', new_passage_path %>

Aeroporto2/app/views/passages/new.html.erb
<h1>New Passage</h1>

<%= render 'form' %>

<%= link_to 'Back', passages_path %>

Aeroporto2/app/views/passages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Font:</strong>
  <%= @passage.font %>
</p>

<p>
  <strong>Destiny:</strong>
  <%= @passage.destiny %>
</p>

<%= link_to 'Edit', edit_passage_path(@passage) %> |
<%= link_to 'Back', passages_path %>

Aeroporto2/app/views/routes/_form.html.erb
<%= form_for(@route) do |f| %>
  <% if @route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% @route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hour %><br>
    <%= f.text_field :hour %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Aeroporto2/app/views/routes/edit.html.erb
<h1>Editing Route</h1>

<%= render 'form' %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

Aeroporto2/app/views/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listando Rotas</h1>

<table>
  <thead>
    <tr>
      <th>Hora</th>
      <th>Preço</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= route.hour %></td>
        <td><%= route.price %></td>
        <td><%= route.status %></td>
        <td><%= link_to 'Mostrar', route %></td>
        <td><%= link_to 'Editar', edit_route_path(route) %></td>
        <td><%= button_to 'Destruir', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova rota', new_route_path %>

Aeroporto2/app/views/routes/new.html.erb
<h1>New Route</h1>

<%= render 'form' %>

<%= link_to 'Back', routes_path %>

Aeroporto2/app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hour:</strong>
  <%= @route.hour %>
</p>

<p>
  <strong>Price:</strong>
  <%= @route.price %>
</p>

<p>
  <strong>Status:</strong>
  <%= @route.status %>
</p>

<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>